### ISSUE TITLE
Mark this repository as archived

### ISSUE THREAD

**Issue by PowerKiKi** [creof/doctrine2-spatial#227]
This project [last release](https://github.com/creof/doctrine2-spatial/tags) is from July 2017, so 7 years ago. It [cannot work with Doctrine ORM 3.0](https://github.com/creof/doctrine2-spatial/issues/224), and the [code activity has been _extremely_ low since July 2017 with only 3 commits](https://github.com/creof/doctrine2-spatial/graphs/contributors?from=2017-03-14&to=2024-07-10&type=c).

@djlambert, @sadortun, I would like one of you to merge #226, and then [archive this repository via GitHub settings](https://github.com/creof/doctrine2-spatial/settings#danger-zone). So that the community can organize itself for future developments and consider migrating to alternatives (one of such could be https://github.com/longitude-one/doctrine-spatial).

**Comment by sadortun** [comment]
Hi @PowerKiKi ! 

I'm personally not using the project but many other still do. I think it would be favorable to find another maintainer.

I'm a bit reluctant to merge PRs because I can't test them directly. But if anyone want to do it, it'll be more than welcome.

The project is still used by many.

https://packagist.org/packages/creof/doctrine2-spatial/stats

**Comment by sadortun** [comment]
Closing this in favor of #228
