### ISSUE TITLE
Project relocation ?

### ISSUE THREAD

**Issue by sadortun** [creof/doctrine2-spatial#56]
Hello Derek / Jon,

First of all, thanks for your contribution for the spatial library, it's very useful !

We will be using the spatial library heavily in the next two years and we need to have a stable origin on where to work from.

I think it would be a good idea for the project to be moved to a neutral location where a few moderators could perform the merge and restart the release cycle. There is 10 PR+ waiting, and about 5 active forks which are all going in different directions...

I would suggest to @djlambert  and @ddproxy  merge their branches into a common 'neutral' project. Both major contributors would be administrator of the project.

I've created the organisation https://github.com/FriendsOfDoctrine/doctrine2-spatial  to allow the project to continue growing and have active maintainers. 

Let me know what you think,
Samuel

**Comment by djlambert** [comment]
I sincerely apologize for the silence and stagnation of library. The last
1.5+ years have been an epic whirlwind of activity in both my personal and
professional life, and I've been coming up short on time to devote to it.
I'm humbled by the fact that people find the library useful and desire for
its continued development.

I originally created the library for use in another stalled project, of
which it's an integral component. For this reason I've had some reluctance
ceding sole control of my repository, as changes could potentially cause
unintended issues there. I also understand the implications of concurrent
independent development on multiple separate forks, and agree a single and
actively maintained location would be best for the future of the library.

The first number of PR's submitted were without tests, using non PSR-2 code
formatting, and not practicing the Object Calisthenics concepts I was
working to follow. This caused an undesirable amount of work when merging.
Contribution guidelines where something I wanted to define to document
expectations for PR's and before considering adding additional
administrators.

The last changes I had been working on (sandbox branch) was to separate
some of the discreet functionality into separate libraries to allow using
spatial objects from foreign libraries. In that effort I moved the string
parser into creof/geo-parser and PHP objects into creof/geo. The WKID/WKT
code was next on the list. There's a number of additional innovations I've
thought through since my last commit, including support for 3D coordinates
and cleaning up SRID handling.

I've finally reached a place where I'll be able to resume work on these
projects in the immediate future. This may have little weight based on my
activity and responsiveness to this point, which is completely
understandable. Over the weekend I'll be working through the existing PR's,
exploring changes made in the different forks, and thinking through how and
where I want to focus my efforts and the contributions of others to the
djlambert repo.

Thanks,
Derek

**Comment by ddproxy** [comment]
@djlambert could you contact me directly? Ddproxy@gmail.com or another route - I've come to the same conclusions and had begun work in that direction as well. I'd like to work more closely with you on the things so we don't butt heads. Also, testing. I'm embarrassed I hadn't fully tested my branch with merges - instead I needed those merges immediately for my critical application and cut corners. I have more time to facilitate testing and documentation and I'd like to combine our efforts in a good way.

**Comment by ddproxy** [comment]
On either front I would be happy to begin maintaining an fod package, by the way.

**Comment by sadortun** [comment]
Hi Derek,

Your situation is totally understandable ! It's still great that you manage to get the project that far !  I've already cherry-picked a few of your commits that were improving the docs, for the remaining of the code change i'll have a look later.

I am happy to see that we will be able to continue your work and work toghether in the same direction !

**Comment by djlambert** [comment]
I've converted the user account creof into an organization and transferred the repo to it. You both should have received invites.

**Comment by ddproxy** [comment]
Do you have a chat client we could use to be more, real-time? Would be nice.

-----Original Message-----

**Comment by djlambert** [comment]
I have accounts on most all of them, does any one work better for you? I'm
available any time after 5P Central today.

**Comment by ddproxy** [comment]
Gitter, Skype, hangouts, text. Send via email if you'd rather. It makes sense to 'keep close' so we remain organized.

-----Original Message-----

**Comment by ddproxy** [comment]
@djlambert I'd suggest renaming the team to geospatial something and adding geo-parse and geo repositories. We can then migrate doctrine2-spatial to use geo-parse and geo.

**Comment by djlambert** [comment]
Done.

**Comment by sadortun** [comment]
Great !

**Comment by ddproxy** [comment]
@sadortun please email me (ddproxy@gmail.com) for communication purposes.
